"""Human-readable summaries for revision experiment outputs."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .paths import EXPECTED_PATIENTS, EXPECTED_VISITS, SEED, SOURCE_DATA_PATH


def write_root_readme(root: Path) -> None:
    lines = [
        "# Mind-Echo minimal additive revision experiments",
        "",
        "This directory is additive and reproducible. It does not overwrite legacy runners, legacy experiment outputs, source JSON, or figure/chart files.",
        "",
        "## Source and grouping",
        "",
        f"- Source visit data: `{SOURCE_DATA_PATH}`.",
        f"- Validated manifest size for this run: {EXPECTED_VISITS} visits and {EXPECTED_PATIENTS} unique patients.",
        "- Grouping field: `patient_id` only.",
        "- Grouping limitation: source rows contain no structured `caregiver_id` or `family_id`; these experiments therefore do not claim caregiver- or family-grouped CV.",
        f"- Deterministic seed: {SEED}.",
        "",
        "## Commands",
        "",
        "Run from `D:\\vscode-project\\git-project\\Mind-Echo`:",
        "",
        "```powershell",
        "python analysis/emotion_model/runners/run_mind_echo_revision_main_v2_oof.py",
        "python analysis/emotion_model/runners/run_mind_echo_revision_window_oof.py",
        "```",
        "",
        "## Outputs",
        "",
        "- `manifest/`: fixed `visit_manifest.csv`, `patient_fold_map.csv`, `visit_fold_map.csv`, and `manifest_metadata.json`.",
        "- `main_v2_oof/`: patient-grouped main V2 OOF metrics for four feature modes and two targets.",
        "- `window_oof/`: separate anxiety/depression OOF metrics for windows 4, 6, 8, 10, 12, 15, and `full_text` using the same manifest and patient folds.",
        "- No figures or charts are generated by these runners.",
        "",
        "## Baselines and uncertainty",
        "",
        "For every held-out fold, the majority baseline predicts the training-fold majority label only; ties choose class 0. The seeded random baseline draws Bernoulli labels using the training-fold positive prevalence and deterministic seed/fold/target offsets. Metrics are pooled over OOF rows and include patient-level bootstrap percentile 95% CIs with 2000 draws by default.",
    ]
    root.mkdir(parents=True, exist_ok=True)
    (root / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_main_markdown(path: Path, payload: dict[str, Any]) -> None:
    lines = [
        "# Main V2 OOF revision results",
        "",
        "Patient-grouped 5-fold OOF predictions with fold-local V2 preprocessing and fixed LogisticRegression. Metrics are pooled OOF values; CIs are patient-level bootstrap percentile intervals.",
        "",
    ]
    for target, rows in payload["targets"].items():
        lines.extend([
            f"## {target}",
            "",
            "| Feature mode | BACC | F1 | Recall | Specificity | ROC-AUC | PR-AUC | TN/FP/FN/TP |",
            "|---|---:|---:|---:|---:|---:|---:|---|",
        ])
        for row in rows:
            m = row["metrics"]["model"]["pooled_oof"]
            lines.append(metric_row(row["feature_mode"], m))
        lines.append("")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_window_markdown(path: Path, payload: dict[str, Any]) -> None:
    lines = [
        "# Window OOF revision results",
        "",
        "Each target is evaluated separately. Every window uses the fixed 78-visit manifest and the same patient fold map. The feature mode is fixed before window inspection and recorded in metadata.",
        "",
    ]
    for target, rows in payload["targets"].items():
        lines.extend([
            f"## {target}",
            "",
            "| Window | Feature mode | BACC | F1 | Recall | Specificity | ROC-AUC | PR-AUC | TN/FP/FN/TP |",
            "|---|---|---:|---:|---:|---:|---:|---:|---|",
        ])
        for row in rows:
            m = row["metrics"]["model"]["pooled_oof"]
            lines.append(metric_row(row["window"], m, feature_mode=row["feature_mode"]))
        lines.append("")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def metric_row(label: str, metrics: dict[str, Any], feature_mode: str | None = None) -> str:
    cm = f"{metrics['tn']}/{metrics['fp']}/{metrics['fn']}/{metrics['tp']}"
    values = [
        label,
        fmt(metrics["bacc"]),
        fmt(metrics["f1"]),
        fmt(metrics["recall"]),
        fmt(metrics["specificity"]),
        fmt(metrics["roc_auc"]),
        fmt(metrics["pr_auc"]),
        cm,
    ]
    if feature_mode is not None:
        values.insert(1, feature_mode)
    return "| " + " | ".join(values) + " |"


def fmt(value: float) -> str:
    if value != value:
        return "NaN"
    return f"{value:.3f}"


def write_json(path: Path, payload: dict[str, Any]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
